### ISSUE TITLE
CSS tries to load Awesome Fonts if they're disabled

### ISSUE THREAD

**Issue by kendall** [asciidoctor/asciidoctor#1262]
I don't like the default Awesome Font icons used in admonitions, etc. So I don't have the icons doc attribute set to anything. But rendered HTML still includes attempts to load entypo.* stuff.

**Comment by mojavelinux** [comment]
Kendall, are you referring to Asciidoctor EPUB3 output (epub3 backend) or main HTML5 output (html5 backend)? I ask because the html5 backend doesn't use entypo.

To disable font-based icons in the main HTML5 output, you need to not set the `icons` document attribute, or better yet just forcefully disable it (i.e., `icons!`) just in case it is set in a document. If you still see things loading, could you specify the problematic part of the HTML source in the issue comment?

Btw, you can easily change the font icons by using a custom stylesheet. You can see what you have to override by inspecting the following CSS from the default stylesheet.

```css
.admonitionblock td.icon [class^="fa icon-"]{font-size:2.5em;text-shadow:1px 1px 2px rgba(0,0,0,.5);cursor:default}
.admonitionblock td.icon .icon-note:before{content:"\f05a";color:#19407c}
.admonitionblock td.icon .icon-tip:before{content:"\f0eb";text-shadow:1px 1px 2px rgba(155,155,0,.8);color:#111}
.admonitionblock td.icon .icon-warning:before{content:"\f071";color:#bf6900}
.admonitionblock td.icon .icon-caution:before{content:"\f06d";color:#bf3400}
.admonitionblock td.icon .icon-important:before{content:"\f06a";color:#bf0000}
```

The `content` can be any unicode character (prefixed with a backslash). That will map to whatever font-family you have set for the element. Adjust accordingly.
