### ISSUE TITLE
PDF custom theme - header image doesn't work

### ISSUE THREAD

**Issue by wolandscat** [asciidoctor/asciidoctor#1378]
I have a header settings in the [theme file](https://github.com/openEHR/spec-publish-asciidoc/blob/master/resources/openehr_full_pdf-theme.yml) as follows:

```
header:
  recto_content:
    left: image:./images/openehr-logo-150x50.png
    right: '{chapter-title}'
  verso_content:
    left: '{chapter-title}'
    right: image:./images/openehr-logo-150x50.png
```

The output is that the image path is output in the header, not the image. This doesn't matter if the image is in a sub-directory or the same directory as the theme file (I tried both). The output is this:

![image](https://cloud.githubusercontent.com/assets/1481744/8366791/f737cc5e-1b8f-11e5-9e41-378f33a92b5f.png)

See [the test project](https://github.com/openEHR/spec-publish-asciidoc) in order to reproduce.

**Comment by mojavelinux** [comment]
You seem to be missing the trailing `[]` in the inline image macro.

It should be:

```
header:
  recto_content:
    left: image:./images/openehr-logo-150x50.png[]
    right: '{chapter-title}'
  verso_content:
    left: '{chapter-title}'
    right: image:./images/openehr-logo-150x50.png[]
```
