### ISSUE TITLE
Upgrade to Nokogiri 1.6.x

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#1656]
Upgrade to Nokogiri 1.6.x to coincide with dropping support for Ruby 1.8.

**Comment by mojavelinux** [comment]
Be sure to add the following lines to the Travis CI configuration (.travis.yml) to ensure that the Nokogiri 1.6 gem installs quickly.

```yaml
env:
  global:
    # speed up installation of nokogiri by using system libraries
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=1
```
