### ISSUE TITLE
next_adjacent_block can't handle definition lists

### ISSUE THREAD

**Issue by nik9000** [asciidoctor/asciidoctor#3133]
I have a plugin that calls `next_adjacent_block` on every source listing. When I have a source listing inside of a block inside of a definition list I get an error. Here is the source:
```
== Example
Term::
Definition
+
--
[source,js]
----
stuff
----
--
```

And this is the error message:
```
     Failure/Error: next_block = block.next_adjacent_block
     
     NoMethodError:
       asciidoctor: FAILED: <stdin>: Failed to load AsciiDoc document - undefined method `+' for nil:NilClass
     # /var/lib/gems/2.3.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:226:in `next_adjacent_block'
     # /var/lib/gems/2.3.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:226:in `next_adjacent_block'
     # /var/lib/gems/2.3.0/gems/asciidoctor-1.5.8/lib/asciidoctor/abstract_block.rb:226:in `next_adjacent_block'
     # ./lib/my_stuff/extension.rb:71:in `process_block'
```
