### ISSUE TITLE
Excessive vertical space in AsciiMath equations

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#3407]
AsciiMath content that contains forced line breaks have excess vertical space. A hard line break should appear on very next line. Instead, it appears after a blank line (like a separate paragraph). The extra space also occurs when there are two separate "paragraphs" in an AsciiMath equation.

It seems that there are one two many `<br>` tags being inserted. (Perhaps this is due to a change in MathJax). Visual testing is needed.

**Comment by mojavelinux** [comment]
Rendering issue related to #2497.

**Comment by mojavelinux** [comment]
The problem is that there are one two many `<br>` tags being inserted. When the source is split into separate equations, that's the first break. No `<br>` needed there. The `<br>` tag is only needed for *subsequent* line breaks.

What we can't fix is the excess space added per hard line break. That space is coming from the MathJax styles. Each equation has a margin of `1em 0`. So the first break ends up being more than just a single hard line break. It seems like MathJax is addressing this in the 3.0 release, so we'll have to watch for when that becomes available and fix it then.

**Comment by mojavelinux** [comment]
If you really want to reduce the space at the hard line break, you can add these styles to the output document using docinfo:

```css
.MathJax_Display ~ .MathJax_Display,
.MathJax_PHTML_Display ~ .MathJax_PHTML_Display,
.MathJax_SVG_Display ~ .MathJax_SVG_Display {
  margin-top: -0.75em;
}
```
