### ISSUE TITLE
Only apply stripes to tbody

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#3881]
Only apply stripes to the body of tables. It doesn't make sense to include the stripes for header and footer rows. Plus, it complicates the setting since the count becomes dependent on whether the table has a header row.

Here's the CSS to use:

```css
table.stripes-all > tbody > tr,
table.stripes-odd > tbody > tr:nth-of-type(odd),
table.stripes-even > tbody > tr:nth-of-type(even),
table.stripes-hover > tbody > tr:hover {
  background: #f8f8f7;
}
```
