### ISSUE TITLE
Changing numbering style of qanda?

### ISSUE THREAD

**Issue by rben01** [asciidoctor/asciidoctor#3968]
Is it possible to change the numbering style (HTML `list-style-type`) of qanda lists? I tried

```asciidoctor
[qanda,loweralpha]
question::
answer
```

but it still uses numbers.

**Comment by mojavelinux** [comment]
That's not a feature that AsciiDoc supports right now. However, if you specify loweralpha as a role, then you can reference that role in custom CSS to change the list style type.

AsciiDoc:

```asciidoc
[qanda.loweralpha]
question::
answer
```

CSS:

```css
.qanda.loweralpha > ol {
  list-style-type: lower-alpha;
}
```
