### ISSUE TITLE
Disable user select for inline line numbers

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#4128]
When the syntax highlighter is configured to use the inline linenums mode (e.g., `pygments-linenums-mode=inline`), the default stylesheet should prevent the line numbers from being selected (i.e., make the non-selectable). This allows the user to copy the code without the line numbers being caught up in the selection.

Add the following rule to the default stylesheet:

```css
pre.pygments span.linenos {
  user-select: none;
}
```

Or, to prevent accidentally grabbing the linenums column, add it to the td.linenos as well:

```css
table.linenotable td.linenos {
  user-select: none;
}
```

Also add the following rule to the default CodeRay stylesheet:

```css
.CodeRay span.line-numbers {
  user-select: none;
}
```
