### ISSUE TITLE
Restrict width of linenos column in output for source block in table linenums mode

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#4137]
If a source block has linenums enabled, and the source highlighter is configured to use the table linenums mode, update the default stylesheet to restrict the width of the linenos column to the minimum width needed. This change accomplishes two things:

* Prevents the linenos column from using more space than it needs and cutting into the code column
* Allows any line highlights to span the width of the block

There are at least three ways to do this:

1. Set the width of the linenos column to 0.01%

    ```css
    table.linenotable td.linenos { width: 0.01% }
    ```

    (this is the approach used by GitHub)

2. Set the width of the table to 100% and the width of the linenos column to 0%

    ```css
    table.linenotable { width: 100% }
    table.linenotable td.linenos { width: 0% }
    ```

3. Set the width of the table to 100% and use a colgroup to set the column widths

    ```css
    table.linenotable { width: 100% }
    ```

    ```html
    <colgroup><col><col width="100%"></colgroup>
    ```

I link the solution (1) because it is the least invasive and will work with Pygments output too.

As a side node, ensure the `word-wrap` on the cell is set to normal to prevent the line number from breaking. (The default stylesheet already sets this property on both table and pre).
