### ISSUE TITLE
Hide built-in marker on summary element in Safari when using default stylesheet

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#4162]
The default stylesheet provides a custom marker on the summary element to unify the appearance across browsers. However, the built-in marker is still showing up in Safari. Safari doesn't seem to remove the marker when the display is set to block like other browsers. Instead, it requires the pseudo-element `-webkit-details-marker` to be hidden using this rule:

```css
details > summary::-webkit-details-marker {
  display: none;
}

```

Safari also adds an ugly border around the summary element when it is clicked. This can be removed using the following rule:

```css
details > summary {
  outline: none;
}
```
