### ISSUE TITLE
Map align attribute on table to align roles

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#4211]
To be consistent with block images, which can also have a restricted width, the value of the align attribute on a table should be mapped to the equivalently named align roles (left, center, right). This allows a table to be centered either using the align attribute:

```
[width=50%,align=center]
|===
|a | b
|===
```

or the role:

```
[.center,width=50%]
|===
|a | b
|===
```

The output in both cases is the same.

**Comment by mojavelinux** [comment]
AsciiDoc.py supports this notation, though it outputs the CSS into the style attribute on the HTML table tag.

**Comment by mojavelinux** [comment]
One open question is how to handle left and right alignment. Currently, the left and right roles float the object. That gives different behavior than using an automatic margin. I wonder whether the existing left and right roles should be renamed to float-left and float-right, and left and right should only adjust the margin.

```css
.center, .left, .right {
  margin-left: auto;
  margin-right: auto;
}

.left {
  margin-left: 0;
}

.right {
  margin-right: 0;
}

.float-left {
  float: left;
}

.float-right: {
  float: right;
}
```

Most CSS frameworks use the class names `float-left` and `float-right` in this way. It's less typical to see the bare `left` and `right`, though that would more closely match with the AsciiDoc tradition. It may be that we need a separate issue to resolve it.
