### ISSUE TITLE
Enable sidebar toc for small screens

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor#628]
As part of the responsive behavior of the default stylesheet, the sidebar returns to the content body once the screen width drops below the break point width. This width is currently 1280px, the minimum width of a "medium" screen as defined by Foundation. Based on feedback we've received, this break point is too conservative.

Instead, the sidebar should remain until the "small" screen break point, which is 768px.

To ensure that enough room is left for the content, the width of the sidebar and font size should be reduced between the small and medium breakpoints.

Something roughly like:

``` css
@media #{$small} {
  body.toc2 {
    padding-left: 15em;
  }

  #toc.toc2 {
    width: 15em;
  }
  #toctitle {
    font-size: 1.2em;
  }
  & > ul {
    font-size: .9em;
  }
}

@media #{$medium} {
  body.toc2 {
    padding-left: 20em;
  }

  #toc.toc2 {
    width: 20em;
  }
  #toctitle {
    font-size: 1.375em;
  }
  & > ul {
    font-size: .95em;
  }
}
```
